apiVersion: apps/v1
kind: Deployment
metadata:
  name: uk-property-api-deployment
spec:
  selector:
    matchLabels:
      app: uk-property-api
  replicas: 1
  template:
    metadata:
      labels:
        app: uk-property-api
        env: development
    spec:
      containers:
      - name: uk-property-api
        image: gcr.io/personal-site-283305/propertyapi:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: uk-property-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: uk-property-api